Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/parser.py", line 683, in block_content
    for t in self.subautomaton(
  File "/usr/lib/python3/dist-packages/snakemake/parser.py", line 119, in subautomaton
    return self.subautomata[automaton](
KeyError: 'template_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/__init__.py", line 479, in snakemake
    workflow.include(
  File "/usr/lib/python3/dist-packages/snakemake/workflow.py", line 911, in include
    code, linemap, rulecount = parse(
  File "/usr/lib/python3/dist-packages/snakemake/parser.py", line 818, in parse
    for t, orig_token in automaton.consume():
  File "/usr/lib/python3/dist-packages/snakemake/parser.py", line 105, in consume
    for t, orig in self.state(token):
  File "/usr/lib/python3/dist-packages/snakemake/parser.py", line 761, in python
    for t in self.subautomaton(token.string).consume():
  File "/usr/lib/python3/dist-packages/snakemake/parser.py", line 105, in consume
    for t, orig in self.state(token):
  File "/usr/lib/python3/dist-packages/snakemake/parser.py", line 177, in block
    for t in self.block_content(token):
  File "/usr/lib/python3/dist-packages/snakemake/parser.py", line 688, in block_content
    self.error(
  File "/usr/lib/python3/dist-packages/snakemake/parser.py", line 116, in error
    raise SyntaxError(msg, (self.snakefile.path, lineno(token), None, None))
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 164
SyntaxError: Unexpected keyword template_file in rule definition

SyntaxError in line 164 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Unexpected keyword template_file in rule definition (snakefile, line 164)
